version: '3'

#VOLUMES
# volumes:
#   my-dir:
#     dirver

#NETWORK
networks:
  web-net:
    external: true

#SERVICES
services:
  question-eiu-spa:
    hostname: question-eiu-spa
    container_name: question-eiu-spa
    image: huynhcuongem75/question-eiu-spa:v1.0
    build: .
    restart: always
    networks:
      - web-net
    ports:
      - 2011:80
